name: Build
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Configure Git
        run: git config --global user.email "167962724+WAWAWOGO@users.noreply.github.com" && git config --global user.name "WAWAWOGO"
      - name: Apply patches
        run: ./gradlew applyPatches --stacktrace
      - name: Build Paperclip Jar
        run: ./gradlew createReobfPaperclipJar --stacktrace
      - name: Upload Paperclip Jar
        uses: actions/upload-artifact@v3
        with:
          name: linearpurpur.jar
          path: build/libs/scambukkit-paperclip-*-reobf.jar
