name: Upstream
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */48 * * *"
jobs:
  upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
      - name: Configure Git
        run: git config --global user.email "action@github.com" && git config --global user.name "Github Action"
      - name: Update upstream
        run: |
          ./scripts/updateUpstream.sh
      - name: Apply patches
        run: ./gradlew applyPatches --stacktrace
      - name: Build Paperclip Jar
        run: ./gradlew createReobfPaperclipJar --stacktrace
      - name: Upload Paperclip Jar
        uses: actions/upload-artifact@v4
        with:
          name: linearpurpur-artifacts
          path: build/libs/linearpurpur-paperclip-*-reobf.jar
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
